### ISSUE TITLE
Create Issue template

### ISSUE THREAD

**Issue by mihok** [minimalchat/operator-app#58]
Currently creating issues is a wild west, before we go "Open Source ready" and post onto Hacker News, we should setup a template for issues

**Comment by teesloane** [comment]
I'll get on this for every repo. [Kent C Dodds](https://github.com/kentcdodds/generator-kcd-oss/tree/master/generators/app/templates/github) has some pretty good boilerplate. I'll make a PR with something like that and then we can refine.

**Comment by teesloane** [comment]
#59

**Comment by mihok** [comment]
Done on #59
