### ISSUE TITLE
Fix application menu items

### ISSUE THREAD

**Issue by mihok** [minimalchat/operator-app#60]
Some menu items were added at the very beginning of the operator app's life. We probably dont need some of them, but others we can get working.

Preferences should open the Settings window that was implemented in #39 (maybe renamed too? or Settings renamed to Preferences?)

**Comment by teesloane** [comment]
can you hmu with what bare minimum we need in the menu before I start repairing it ? ⚒

**Comment by mihok** [comment]
Probably not close window, I'm ok with keyboard shortcuts and close conversation

**Comment by mihok** [comment]
Honestly not opposed to removing all those items

**Comment by mihok** [comment]
For now..

**Comment by teesloane** [comment]
give me a list of what you _need_?

**Comment by teesloane** [comment]
I removed `Edit`, ;
 `Help` is functional -- it is just two links (one to the repo, the other to the repo/issues)...

What is needed under `Electron`/ (the app name) ?

**Comment by teesloane** [comment]
`close window` and `quit` are the same  no?

**Comment by mihok** [comment]
Whoa son, why remove Edit? Its all default OS functionality :(

**Comment by mihok** [comment]
yeah Quit > Close Window

**Comment by teesloane** [comment]
can this be closed?

**Comment by mihok** [comment]
Fixed with #65 and #70 :trollface:

**Comment by mihok** [comment]
![](https://s-media-cache-ak0.pinimg.com/236x/0f/41/04/0f410478ffd64e098cb90b203c36f66c.jpg)

**Comment by teesloane** [comment]
LOL YES
