### ISSUE TITLE
Menu-less bar doesn't look super happy

### ISSUE THREAD

**Issue by mihok** [minimalchat/operator-app#73]
Copied over from https://github.com/minimalchat/client/issues/38 (which was the wrong repo)

![](https://user-images.githubusercontent.com/12987958/30669463-75a5cda4-9e2c-11e7-94c9-931302125103.png)

![](https://user-images.githubusercontent.com/12987958/30669526-ab22745a-9e2c-11e7-8c58-2c2364e6fd22.png)

**Comment by mihok** [comment]
Example from Discord
![](https://user-images.githubusercontent.com/113275/30669785-98436ea6-9e2d-11e7-87e8-c9668c040067.png)

**Comment by teesloane** [comment]
I think we should follow up on what @broneks was saying about considering combining the two left panes into one. I talked it over with a UX person and they seemed to have some ideas for it. Might be a post release kind of change tho 🤔
