### ISSUE TITLE
"mark as done" button causes chat to disappear and is no longer reachable via navigation

### ISSUE THREAD

**Issue by broneks** [minimalchat/operator-app#84]
What you did:
- create a chat
- mark as done

What happened:
- blank screen and following console error:
<img width="991" alt="screen shot 2017-09-23 at 21 17 13" src="https://user-images.githubusercontent.com/4494382/30778466-9b030d3a-a0a4-11e7-8870-1680b123edab.png">

**Comment by broneks** [comment]
I think this happens when a chat that no longer exists on daemon is persisted (i.e. when daemon is restarted but the browser still has an old chat id in local storage).

**Comment by broneks** [comment]
Or it happens when refreshing the operator-app browser window.

**Comment by teesloane** [comment]
yeah, I noticed this happening on refreshing the window. Going to dive into this now, hopefully it's small! 🐛
